New /user-guides section
datocms/new-website pull request #59
Opened 2024-05-02 13:36 UTC by marcomezzavilla

2024-05-02 13:52 UTC, stefanoverna requested changes
Ok, primo round

2024-05-02 13:52 UTC, stefanoverna commented on components/PrettyDuration/index.jsx
> +export default function PrettyDuration(seconds) {
questo non è un componente react ma una funzione quindi non dovrebbe iniziare con la maiuscola, ne stare sotto 'components/' ma 'utils/'.

Magari la chiamerei in modo meno vago "formatVideoDuration"?

2024-05-02 13:52 UTC, stefanoverna commented on pages/user-guides/[...chunks]/index.jsx
> +  return (
sono confuso. qui sotto a volte controlli se item c'è (in vario modo, `item && ...`, oppure `item?.xxx`) altre volte invece ci accedi secco. questo mi fa pensare che item ci sia sempre, altrimenti si spaccherebbe nelle volte in cui ci accedi secco.

c'è da normalizzare la situazione, non solo su item, ma in generale, seguendo lo stesso ragionamento. se una cosa c'è sempre, rimuoviamo i conditionals che appesantiscono la lettura.

2024-05-02 13:52 UTC, stefanoverna commented on pages/user-guides/[...chunks]/index.jsx
> +                              {episode?.video?.video?.duration && (
stessa cosa qui. c'è un pullulio di `?.` che generano ansia. ora ho reso il campo video obbligatorio, e DEVE essere un formato video, quindi per esempio qui la condizione `episode?.video?.video?.duration` non dovrebbe esserci proprio, perchè il campo "video" c'è sempre, ed è sempre un video, quindi video.video c'è sempre. se se c'è video.video, è garantito che c'è il duration.

2024-05-02 15:28 UTC, marcomezzavilla commented on pages/user-guides/[...chunks]/index.jsx
> +                              {episode?.video?.video?.duration && (
Vero. La pioggia di condizionali è iniziata quando c'era un solo video caricato, ma effettivamente alcuni check erano totalmente inutili.

2024-05-03 11:49 UTC, stefanoverna requested changes

2024-05-03 11:49 UTC, stefanoverna commented on pages/user-guides/style.module.css
> +    font-size: clamp(18px, calc(18px + 3vw), 48px);
Questa roba clamp probabilmente l'hai vista da altre parti, ma non la generiamo mai a mano. È una utility si chiama [rfs()](https://www.npmjs.com/package/rfs) ([esempio](https://github.com/datocms/new-website/blob/feat/user-guides/components/CreateModularBlocks/style.module.css#L8))

2024-05-06 12:56 UTC, merged